###############################################################################

# Application Information
application: gae-skyhook
version: 1

# Application Parameters
default_expiration: "12d 12h"
runtime: python27
threadsafe: yes
api_version: 1
handlers:

###############################################################################

# Skyhook Elements
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /favicon.ico
  static_files: templates/favicon.ico
  upload: templates/favicon.ico

- url: /templates/(.*)/css/(.*)
  static_files: templates/\1/css/\2
  upload: templates/(.*)/css/(.*)
  http_headers:
    Vary: Accept-Encoding

- url: /templates/(.*)/img/(.*)
  static_files: templates/\1/img/\2
  upload: templates/(.*)/img/(.*)
  http_headers:
    Vary: Accept-Encoding

- url: /templates/(.*)/js/(.*)
  static_files: templates/\1/js/\2
  upload: templates/(.*)/js/(.*)
  http_headers:
    Vary: Accept-Encoding

# Application Handlers
- url: /account/.*
  script: main.app
  secure: always

- url: /.*
  script: main.app
  secure: never

###############################################################################

# App Engine Redirects
builtins:
- admin_redirect: on

# Development Libraries
libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: latest
  
- name: markupsafe
  version: latest

###############################################################################
